WINDOW_TIME_THRESHOLD = 200
DISPERSION_THRESHOLD = float(0.025)

FIXATION_VELOCITY_THRESHOLD = float(0.003)

#machine learning consts
WINDOW_MACHINE_LEARNING_TIME_THRESHOLD = 50
ANGLE_X_DEGREES = 32
ANGLE_Y_DEGREES = 40