WINDOW_TIME_THRESHOLD = 200
DISPERSION_THRESHOLD = float(0.0015)

FIXATION_VELOCITY_THRESHOLD = float(0.001)

#machine learning consts
WINDOW_MACHINE_LEARNING_TIME_THRESHOLD = 100
ANGLE_X_DEGREES = 32
ANGLE_Y_DEGREES = 40